server:
  port: 9002

spring:
  application:
    name: lagou-cloud-gateway
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: service-autodeliver-router # 我们自定义的路由ID，保持唯一
          #uri: http://127.0.0.1:8092
          uri: lb://lagou-service-autodeliver  #gateway网关从服务注册中心获取实例信息然后负载后路由
          predicates: #断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
          - Path=/autodeliver/**
        - id: service-resume-router      # 我们自定义的路由ID，保持唯一
            #uri: http://127.0.0.1:8081       # 目标服务地址
          uri: lb://lagou-service-resume
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
          - Path=/resume/**

            #截取url
            #filters:
              #- StripPrefix=1


#注册到eureka注册中心
eureka:
  client:
    service-url:
      #集群模式
      defaultZone: http://eureka01:8761/eureka,http://eureka02:8762/eureka
  instance:
    prefer-ip-address: true #使用ip注册 否则就使用主机名(兼容老的版本，老版本显示主机名)
    #自定义实例显示格式，加上版本号
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@